import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'aos/dist/aos.css';
/* Created by VpnWAN *//* Created by VpnWAN *//* Created by VpnWAN *//* Created by VpnWAN *//* Created by VpnWAN */

const geistSans = Geist({
  variable: "--font-geist-sans",/* Created by VpnWAN *//* Created by VpnWAN *//* Created by VpnWAN *//* Created by VpnWAN *//* Created by VpnWAN */
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
/* Created by VpnWAN *//* Created by VpnWAN *//* Created by VpnWAN *//* Created by VpnWAN */
export const metadata = {
  title: "CHRONO-WATCHES",
  description: "Generated by create next app",
};

/* Created by VpnWAN *//* Created by VpnWAN *//* Created by VpnWAN *//* Created by VpnWAN *//* Created by VpnWAN */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>/* Created by VpnWAN *//* Created by VpnWAN *//* Created by VpnWAN *//* Created by VpnWAN *//* Created by VpnWAN *//* Created by VpnWAN *//* Created by VpnWAN */
  );
}
